### ISSUE TITLE
Rooms/circles issues

### ISSUE THREAD

**Issue by gulien** [thecodingmachine/workadventure#104]
I've encountered the following issues related to rooms (aka circles) 😄 

- We cannot be more than 3. As far as I know the maximum is 4, no?
- Sometimes 3 people can be in the same circle but only one of them can see the other two, while the other two can only see him.
- Circles are sometimes still displayed even if nobody is inside.

**Comment by gulien** [comment]
* Sometimes when being outside of a circle, the last two members can still talked to each other and it is not possible to join another circle.

**Comment by moufmouf** [comment]
> Sometimes when being outside of a circle, the last two members can still talked to each other and it is not possible to join another circle.

There is an issue with the new way we handle IDs. Since user ids are depending on the connection, if connection to the back is closed and open again, new ids will be generated... and a second WebRTC connection will be established with the same users.
We should make sure that all WebRTC connections are closed at the moment we reconnect to the server (we can keep them open while the server is down in order not to interrupt a conversation, even if the back is down)
