### ISSUE TITLE
new remote code execution

### ISSUE THREAD

**Issue by jonnytest1** [thecodingmachine/workadventure#1121]
@moufmouf  send over twitter again

**Comment by jonnytest1** [comment]
export interface UnsafeString extends String {

}

i think it would be a good idea to type strings coming from the backend with this interface 
youd have to use toString() to get the value or i suppose you could make a service method like escapeHtml that takes unsafeString and returns a safe(normal) one

**Comment by moufmouf** [comment]
Oh jee!.... thanks! Looking at it.

**Comment by jonnytest1** [comment]
https://github.com/jonnytest1/workadventure/commit/c50a48719bd305cc3dedf0d6f8ff24cb029d7683

here is an example of an unsafeString interface :)

**Comment by moufmouf** [comment]
@jonnytest1 this is extremely cool.
Although I'm still struggling on how to use that.

Unsafe strings are coming from the backend. The backend is sending data via Protobuf, so the serialization / deserialization is handled by Protobuf. Ideally, I should find a way to tell the Protobuf Typescript code generator to cast strings into UnsafeString by default. But I haven't found how to do that yet!
Are you doing things in another way? Any idea?

**Comment by jonnytest1** [comment]
if everything else fails you should stil lbe able to use a generic typescript object that recursively replaces every string type with unsafeString

~ type UnsaveObject<T> = {[Key in keyof T]:T[Key] extends string ? UnsafeString : UnsafeObject<T[Key>} (probably gotta do some primitves handling)

**Comment by moufmouf** [comment]
Wooo! Still more wizardry :rofl: 

This could actually work if objects were stored as interfaces. I could use this actually: https://stackoverflow.com/questions/60437172/typescript-deep-replace-multiple-types

Now, the problem is that the generated code is generating classes:

```
export class CharacterLayerMessage extends jspb.Message { 
    getUrl(): string;
    setUrl(value: string): CharacterLayerMessage;

    getName(): string;
    setName(value: string): CharacterLayerMessage;
}
```

And I'm pretty unsure we can do something about changing the return type of the getters. (if you know a way, I'm interested.

I could switch the Proto to Typescript generator to a generator that is generating Typescript interfaces though (like this one: https://github.com/stephenh/ts-proto#wrapper-types ) but that is quite a lot of work

**Comment by jonnytest1** [comment]
ReturnType<T[Key]> extends string ? :  ()=> UnsafeString   - should work

**Comment by moufmouf** [comment]
I'm closing this as the remote code execution is fixed. We can keep the discussion on #1136
