### ISSUE TITLE
Jitsi and workadventure on a single host

### ISSUE THREAD

**Issue by Lithimlin** [thecodingmachine/workadventure#1387]
I'm currently trying to set up the [docker version of jitsi](https://github.com/jitsi/docker-jitsi-meet) and workadventure on a single host. Jitsi has an ["example configuration" for traefik v2](https://github.com/jitsi/docker-jitsi-meet/tree/master/examples/traefik-v2) which is unfortunately not very helpful. I have tried to set up jitsi as described there but there seem to be more configurations of traefik made which were not explained (like the `video` entrypoint).

Does anyone have experiences with using both services on a single host and could share their configurations?

Since attempting to use traefik in the jitsi setup, I also get "DNS resolution failed" errors from the pusher. Does anyone have a clue where these could be coming from?

**Comment by Lurkars** [comment]
I personal have Jitsi running on same host, but not inside docker. Also my setup is not completely assumable because it's not primarily for WA. So that's why I cannot confirm is this is working, but here is a guide linked multiple times about self hosting WA and it also includes part for Jitsi:
https://wiki.techinc.nl/Work-Adventure/install#Jitsi_2 (Kudos belongs to the authors, I am not related to it!)

**Comment by Lithimlin** [comment]
Thanks a lot! That really helped ironing out the last issues. Now everything is back to its previous three-quarter-working state
