### ISSUE TITLE
Specifie Iframe size/width in your maps

### ISSUE THREAD

**Issue by LancelotBompard** [thecodingmachine/workadventure#1389]
Hello,

I've used Iframes in my maps and i've seen it takes about 50% width of the window size. I'd like to make it take 80% of that width, but I don't know how to do that. 
Did anyone try that already ?

**Comment by tabascoeye** [comment]
sort of like #1076.

If you are OK with _all_ cowebsites/Jitsis opening to 80% width, you can just hardcode it here:
https://github.com/thecodingmachine/workadventure/blob/eb895ceb58ef83e115d30b8f3c37e275318433af/front/style/cowebsite.scss#L55

and set that to 80% instead of 50%.

If that should be dynamic or configurable on a per-layer basis, then lots more work would need to be done

**Comment by tabascoeye** [comment]
@LancelotBompard ??? why did you close this?

**Comment by LancelotBompard** [comment]
Oh my bad, I did not notice I'd closed it, was not intended, reopening it now.
