### ISSUE TITLE
is unable to run WA on 2vCpu?

### ISSUE THREAD

**Issue by LOGANLEEE** [thecodingmachine/workadventure#1560]
spec of instance

2vCpu, 4GB RAM, 80SSD( Amazon Lightsail )

but once start docker compose freeze the instance and have to reboot it manually.

that happened quite right after finishing scanning and built Svelt from front1.

any helps....?

**Comment by moufmouf** [comment]
Hey @LOGANLEEE ,

I'm not 100% sure. I must say we never tried to start on such small instances.
Just to be sure, are you useing the docker-compose.yml file at the root of the project or the production one (at contrib/docker/docker-compose.yml) ?

**Comment by flonix8** [comment]
I've had similar issues before. In general, WA (+ Jitsi in my case) runs totally fine on a 2vCPU / 2GB memory instance.
The issue was for me that on every container start the frontend is built using npm, which gobbles up a ton of memory (I had to enable swap space on my 2GB memory instance, otherwise the build crashes).
Maybe try starting the workadventure containers, open htop in another terminal and closely monitor your memory usage. If it exceeds, say, 80%, just enable swap on your machine.

**Comment by tabascoeye** [comment]
Yes, the "webpack" process eats more than 2GB RAM during first build of the "front" container. Thus if you have anything else running on the server which needs RAM as well, use a big swap space.
I run WA comfortably on single CPU 2GB vservers (Hetzner cloud without wanting to advertise), no problems. But for the build, the swap needs to be in place so that wepack is not killed by the Linux OOM-killer

**Comment by pinpox** [comment]
What is the `webpack` step doing exactly, it seems to be run only on startup? Would it be possible to have that only run when building the docker images and not when they container is started? 

After the `webpack` step the containers use a lot less resources, which would allow to run workadventure on much smaller machines

**Comment by tabascoeye** [comment]
Again. Just create swap space and you will be fine with 2GB of ram.

**Comment by LOGANLEEE** [comment]
> Again. Just create swap space and you will be fine with 2GB of ram.

many thanks. I actually moved to 'SkyOffice' from WA to run it but..

the problem was 'Front' as others commented above.

and even other containers are running. front container will be running at the last. ( cuz of building)
