### ISSUE TITLE
Feature Request: Custom Classes for Popups

### ISSUE THREAD

**Issue by Lithimlin** [thecodingmachine/workadventure#1572]
It would be cool if one could add custom css classes to popup windows.
Alternatively (or additionally) it would be nice to be able to change some of the existing classes (regarding popups and others, like `PopUpElement`) in the custom css sheets.
Lastly, it would also be helpful to have the option to have popups not show up on the very top of everything but instead underneath other (default) popups and/or the camera views.

If any of these are already possible just let me know.
Thanks in advance

**Comment by moufmouf** [comment]
Hey @Lithimlin ,

It would indeed be nice to let map authors use custom CSS properties for popups (but also for other CSS elements).

We did not do it yet because I have questions regarding security. I'm not sure whether letting anyone write a custom CSS sheet can be a security issue or not. In particular, I don't know if there is such a thing as "CSS injection". I think some browsers can execute JS in CSS and I fear this might be an attack vector (https://stackoverflow.com/questions/476276/using-javascript-in-css)

Si if anyone reading this issue knows if CSS injection is a thing or not, I'd be interested ;D

**Comment by moufmouf** [comment]
> Lastly, it would also be helpful to have the option to have popups not show up on the very top of everything but instead underneath other (default) popups and/or the camera views.

Unfortunately, the popups cannot be displayed "below" sprites of the map. This is a limitation of the Phaser game engine we use.

**Comment by moufmouf** [comment]
For future reference: the OWASP documentation regarding CSS injection

https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/11-Client_Side_Testing/05-Testing_for_CSS_Injection

**Comment by gparant** [comment]
Hi @Lithimlin, I close this issue, don't hesitate to contact us if you need more information 🚀
