### ISSUE TITLE
Dockerfile front error : The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by rllola** [thecodingmachine/workadventure#1734]
I am updating my workadventure setup to 1.7.2 and couldn't build the docker container for front.

I have the following error:
```
error @typescript-eslint/eslint-plugin@5.6.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.15.1"
error Found incompatible module.
```
The dockerfile is showing that we are using 14.15.4 ?
https://github.com/thecodingmachine/workadventure/blob/develop/front/Dockerfile#L1

**Comment by rllola** [comment]
I have been able to fix by changing this line:
https://github.com/thecodingmachine/workadventure/blob/develop/front/Dockerfile#L18

with
```
RUN yarn install --ignore-engines
```
Doesn't look like a look term solution tho.

**Comment by gparant** [comment]
The property `--ignore-engines` allows package authors to state which node engines are required for the package to work. Basically, which node version is needed.

If you ignore this guidance, you run the risk of installing a package that won't work with the version of node that you ar using because it relies on a feature that your version of node does not support.

I’m not sure that it’s a good thing. If you have this problem, I counsel to execute `docker-compose down` and after up all services with `docker-compose up (-d)`

**Comment by moufmouf** [comment]
Hey @rllola ,

You are perfectly right. I just tested the build script and it fails for me too.

What I don't understand is that it worked in the CI/CD system. I'll have to figure out why.
The correct fix is to upgrade the Node version. I'll look into it. Thanks for opening this issue!

**Comment by moufmouf** [comment]
Ok, I found the issue.
The code is actually correct.
@rllola, you are just facing a Docker image cache issue.


The `thecodingmachine/nodejs:14-apache` but @rllola and I were running an old version of the image on our machine (with an old NodeJS version). This is why the CI/CD pipeline (that has no cache) works correctly.

To update the cache, you can simply run:

```
docker pull thecodingmachine/nodejs:14-apache
```

**Comment by rllola** [comment]
Ah great!

Thank you @moufmouf !
