### ISSUE TITLE
Bug: Broadcast to all maps not working 

### ISSUE THREAD

**Issue by Schroedingberg** [thecodingmachine/workadventure#1953]
The answer in #1765 implies that if the "broadcast to all maps" checkbox is toggled, that this should work then. When I try to broadcast a message to all rooms this way, nothing happens in the UI. 
I get the following output from the pusher logs:

`pusher_1         | (node:89) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500`
`pusher_1         |     at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)`
`pusher_1         |     at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)`
`pusher_1         |     at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:269:11)`
`pusher_1         |     at IncomingMessage.emit (events.js:412:35)`
`pusher_1         |     at endReadableNT (internal/streams/readable.js:1334:12)`
`pusher_1         |     at processTicksAndRejections (internal/process/task_queues.js:82:21)`
`pusher_1         | (node:89) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)`
Did I miss anything in the setup or is this a known problem?

**Comment by moufmouf** [comment]
Hi @Schroedingberg ,

If I remember correctly, "broadcast to all maps" is making a request to the "admin" server to fetch the list of all maps related to the current map. In our SAAS environment, this means: look at all the maps in the same world.

But the notion of world does not exist in WorkAdventure itself (only in our admin backend). 
Since you have pusher logs, I assume you are using your own WorkAdventure deployment.

I must admit we probably failed to test this without an Admin API (which is normal since without an Admin API, you don't have a "admin" tag, so no access to the "broadcast message" button).

Are you using a custom built Admin API?
