### ISSUE TITLE
Authentication for maps

### ISSUE THREAD

**Issue by klausfl** [thecodingmachine/workadventure#2264]
I am the admin for [Thoughtworks](https://www.thoughtworks.com/)' workadventure instance. We run workadventure with `DISABLE_ANONYMOUS=true` and use OpenID Connect using `OPID_`. 

One of the risks we identified is sensitive information embedded in maps being world-readable. For example, a map could contain an external URL with sensitive URL parameters.

`maps`, unlike other public endpoints, does not seem to have a possibility for enforcing authentication. Is that correct?

One challenge is that the map json is loaded through an XHR which is triggered by Phaser.  So we were wondering - what would it take for the map json call to be authenticated?

I could see 2 possibilities
1) Shared secret between pusher and maps. [Phaser supports custom headers through the XHRSettingsObject](https://newdocs.phaser.io/docs/3.54.0/Phaser.Types.Loader.XHRSettingsObject). In the call to `{pusher}/maps`, return a customer header or basic auth credentials (potentially retrieved and forwarded from `admin`) which `front` forwards to Phaser through `Loader` (I'm not 100% on how the current implementation works)
2) Forward jwt token to maps. Likewise, Phaser could be instructed to forward the player's current token via the the `Authorization: Bearer {token}` header. When using `DISABLE_ANONYMOUS`, at this stage, a token should always be present. This allows the `maps` host to perform token validation. This would be our preferred solution.

What do you think? Based on your preference for any particular solution, I'm happy to provide a pull request for discussion.

Merci beaucoup,
Klaus

**Comment by moufmouf** [comment]
Hi @klausfl !

Do you have a strong need for this "now"?
I'm asking because we are starting working on a WorkAdventure map editor. As part of this, the way maps are handled could be completely changed. In particular, it is possible that in the future, maps will be loaded from the pusher or the back component (and then forwarded to the front).

In this case, it would somehow change the way you can implement security. You could basically put the maps in a server only accessible to the pusher and back servers.

So if you are not in a hurry, I'd suggest to wait and see how this changes.
If you are in a hurry, I'd probably prefer solution 1 (since using an admin, one could provide different authentication tokens based on the map that is queried)

What do you think?

**Comment by klausfl** [comment]
Hi @moufmouf , I see that the work on the map editor has started. I see the [docs](https://github.com/thecodingmachine/workadventure/blob/develop/docs/dev/communication-between-services.md) hint at a possibility to load maps via `front -> pusher -> back -> map-storage`, as you outlined. It's not 100% clear yet how (static) map loading will work in the future. Via HTTP or GRPC? In any case, better to hold off and wait for the editor feature.

If you could take into account the use case of authentication for maps content meanwhile?
