### ISSUE TITLE
Do Not Disturb zone

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#254]
Hey!

It could be great to have a zone where you are in a "do not disturb" mode.
Meaning:
- Nobody can talk to you
- Nobody can see you
→ Like "I don't want interactions with me, leave me alone"

This could be:
- A working space
- A zen room
- A cave…

We have this issue with my team when somebody gets a visitor and wants some privacy.
They move away from the current discussion but somebody else can still come by and enter in their circle, which will activate the microphone.

So, like the Jitsi rooms, it could be great to define such space.

**Comment by moufmouf** [comment]
Hey Jacques!

I actually added yesterday a "silent zone" (see https://workadventu.re/create-map.html#making-a-silent-zone)
When in a silent zone, noone can talk to you.

The problem is that... noone can talk to you (when you enter the silent zone, any conversation in progress is closed).
And from a user experience, I feel it would be hard for 2 users to start a conversation outside de "do not disturb zone" and move inside the zone without breaking the circle.

Maybe the best idea would be to add a button allowing to "lock" a circle, effectively preventing anyone to enter it. The circle might turn to red to show other users that it cannot be entered.

Would that make sense?

**Comment by jacquesbh** [comment]
Actually the Silent Zone is what I was searching for. To allow private real life!

Your idea of locking the circle is nice too, I like it.
So, it's another idea I think, this one got its response!
