### ISSUE TITLE
Breaking changes on master branch in getArea API

### ISSUE THREAD

**Issue by taksan** [thecodingmachine/workadventure#2614]
On WA version 1.11.4, I was able to use the `WA.room.area.get` function to get areas that were in other objectgroups besides floorLayer. 

I'm not sure that was an unintended feature, but it was useful for me because I used a separate objectgroup to place certain area objects and then I scanned all areas in that group to automatically setup several jitsi rooms (that way I was able to avoid duplicating quite some configuration).

Is this a real bug?

**Comment by moufmouf** [comment]
Ping @Waclaw-I

**Comment by taksan** [comment]
Well, I thought `WA.room.area.get` was broken only for areas that were not in floorLayer, but it is actually broken to get any area predefined in the map, regardless of the object layer used, so I'm pretty sure that is bug, as it worked fined until 1.11.4. I figured that the culprit is in this line:

https://github.com/thecodingmachine/workadventure/blob/413a8ff533537c4e7c75d093b1fe83fdfa396c01/front/src/Phaser/Game/DynamicAreaManager.ts#L78

The API now is able to retrieve only dynamic areas, that is, areas that have been created with the createdArea method. In fact, I've tested the API and I was able to get dynamically created areas.

**Comment by Waclaw-I** [comment]
Hey there @taksan

We are currently working on a live map-editing feature which introduced some constraints. One of them is a split into two different Area Object types:
- Static (ones defined from Tiled and stored in map .json file)
- Dynamic (created by using Area API, existing in memory)

Due to the nature of "live" editing, we do not want API to be able to edit Static Areas. I apologize for this inconvenience, we did not intend to introduce a breaking change.
Maybe you could also create given areas from API (so they will be marked as Dynamic ones) and then proceed with applying configs?

Cheers

**Comment by taksan** [comment]
Yes, I can auto create areas based on the static areas, that is the workaround I was planning in case the fix would take too long (and it seems now, there's nothing to be fixed, as it is by design).

Considering that's by design, I suggest you make it clear in the area documentation that constraint and that it is a behavior change from previous versions.

thanks
