### ISSUE TITLE
WA doesn't found mp3 music path 

### ISSUE THREAD

**Issue by GregLebreton** [thecodingmachine/workadventure#2800]
Hi guys,
I'm building a custom map with music area.
I already did it on another map and it worked but on this one: https://GregLebreton.github.io/gregandev-map/map.json, 
And this one for zelda fans: https://GregLebreton.github.io/gregandev-map/map3.json.
It won't find the file whatever path I put it in (src/assets or public/).

If anybody have an hint or a clue about what I am doing wrong...

**Comment by LindezaGrey** [comment]
First of all, you are building the map with github workflow - try to build it locally and see what`s in the generated "dist" folder. This is what is hosted on github pages.
In this file:

https://github.com/GregLebreton/gregandev-map/blob/master/tsconfig.json

it looks like only the "src" folder is included (section "include"). You can try to add "assets" there. Alternatively for a sanity check, you could link the assets directly from your github repo in the map like so:

https://github.com/GregLebreton/gregandev-map/blob/master/assets/music/music.mp3?raw=true

Did it help?

**Comment by GregLebreton** [comment]
Hi @LindezaGrey  and thank you for your answer.
It works locally with the mp3 audio, but in prod WA server fails to find the file, I don't get it, I tried to put all assets in src/ and to put absolute link in mp3 file réference on the map but nothing seems to change...

**Comment by LindezaGrey** [comment]
I just looked at your commits. Don't get frustrated, i know it can be quite annoying sometimes :D 

I would revert the commits you did, since things got worse i suppose - especially deleting the vite.config
The map is not working anymore, is it?

I didn`t want you to move the "asset" folder to the "src" folder, but to modify the tsconfig.json (but not 100% sure if this would work anyway)

i guess a good next step would be: revert back as much as possible - then when the map works as before, host the mp3 somewhere you know it works (dropbox, google etc.) and try to load from there directly - just to make sure it actually works with the file

**Comment by GregLebreton** [comment]
The absolute link did the trick! :D (along with the vite.config coming back).
It's weird cause with another map, the relative path from the map works...
Thanks!
