### ISSUE TITLE
v1.13.5 has issues with /login

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2804]
The latest released version (v1.13.5) has issues when hitting the "/login" endpoint sometimes.
(at least, this was tested in /login + whitelabel scenarios on the SAAS)

A JSON error page ("world not found" JSON message) is displayed.

v1.13.4 does not have this problems.
This might be linked to #2780

**Comment by LindezaGrey** [comment]
Upon further investigation if it is a bug or a feature i start thinking that this redirect is not on purpose. In the current version, if i click on sign-in it routes me just to /login which gets interpreted as a playUri

![image](https://user-images.githubusercontent.com/39629455/201965221-f9fca527-83bb-448f-83e3-bc8d49720170.png)

and thus has to be handled in the adminApi (if present). This has the problem, that all context about the real playUri gets lost, so even if i can send a redirect (in my case play.localhost/login-screen?playUri=) you can't be redirected to your original map. 

Since the "/login" is sent as playUri to the adminAPI i can imagine why you receive the "world not found" error.

**Comment by moufmouf** [comment]
Closed by #2806 

Note: the "register" button should have an environment variable tied to it. This is weird. Ping @gparant
