### ISSUE TITLE
Docker Compose fail

### ISSUE THREAD

**Issue by kamikazebr** [thecodingmachine/workadventure#289]
Hi!

First of all, I have to say that this project is amazing!

My problem is that when using the docker-compose the back and front services fail with

```
yarn run v1.22.5
back_1 | error Couldn't find a package.json file in "/ usr / src / app"
```

And the website service fail with 

`npm WARN saveError ENOENT: no such file or directory, open '/var/www/html/package.json'`

Which leads me to believe that the **volumes** are not being mounted correctly.

I suspect that because I am using WIndows Home, which does not allow the use of Docker Desktop which has a more updated version, it may be one of the causes.

Still, the behavior is strange, building as **dockerfile** does not present the same error.

I have already changed docker-compose.yaml in countless ways like adding **working_dir** and etc.

But it continues to fail.

Any suggestion?

------------------------------
OS: Windows Home Single License
Docker Toolbox v19.03.1
docker 19.03.1
docker-machine 0.16.1
docker-compose 1.24.1
Kitematic 0.17.7
Boot2Docker ISO 19.03.1
VirtualBox 5.2.20

**Comment by moufmouf** [comment]
Hey @kamikazebr ,

I must admit I've never tested starting WorkAdventure on Windows. As far as I remember, Docker on Windows can only map volumes on a part of the hard drive (I think by default, it can map files if they are in your "Document" folder, but not if they are somewhere else). Maybe you could try moving WorkAdventure in the "Document" folder and try again?

Otherwise, you could try installing Docker via WSL2 (https://docs.microsoft.com/en-us/windows/wsl/install-win10). In this setup, you install a small Linux kernel in Windows and you run Docker on the Linux kernel. This is known to have good performances.

Let me know if this works!

**Comment by kamikazebr** [comment]
It worked !!

I needed to update my windows and configure the WSL2 backend to run Docker Desktop.

Desktop Docker is so easy to work with, I loved it.

My system was much slower, but I will migrate to Ubuntu soon.

Thank you!

**Comment by moufmouf** [comment]
You are welcome!

I'll see when you try Ubuntu, Docker is so much faster than on Windows or MacOS :)
