### ISSUE TITLE
Unreadable and glitchy font

### ISSUE THREAD

**Issue by piegamesde** [thecodingmachine/workadventure#511]
The pixel font is glitchy at times and doesn't always render as intended. On smaller font sizes it becomes completely unreadable.

![image](https://user-images.githubusercontent.com/14054505/102662255-c4e5a080-417e-11eb-9e30-7901de988e09.png)
![image](https://user-images.githubusercontent.com/14054505/102662266-cc0cae80-417e-11eb-84fd-4a2ad1229be1.png)
![image](https://user-images.githubusercontent.com/14054505/102662274-cdd67200-417e-11eb-9c58-90ab05ffd88f.png)

**Comment by moufmouf** [comment]
Hey @piegamesde ,

Thanks a lot.
Actually, these are 2 different issues.

The issue on the 404 page is due to the font rendering of the engine we are using (Phaser 3). We can try to improve this by changing the font or by making it bigger.

The issue about the player name is harder. I'm not sure why we are seeing it. I believe it could be a rounding error due to the WebGL engine, but I'm not 100% sure... we'll have to investigate that. I'm keeping this issue open in the meantime.
Thanks!

**Comment by gparant** [comment]
I close this issue, we still available if you have any other question.

Thanks for your feedback 💪
