### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#514]
I'll use this issue to document the performance of WorkAdventure regarding Phaser 3 rendering of the maps.

The measures are performed

- on a development environment targetting current develop branch
- on a Dell XPS 9550 (4k display)
- on Chrome
- using the default Floor0 map
- with Phaser limited to 60fps

Test 1: performance as of commit 7bbfa16

![image](https://user-images.githubusercontent.com/1290952/102819562-f30fee00-43d3-11eb-8fe5-26771a3d2f9b.png)

Test 2: Same commit but changing Static layer to Dynamic layer

![image](https://user-images.githubusercontent.com/1290952/102819807-80ebd900-43d4-11eb-8fe9-bfc62c16b719.png)

Note: CPU goes up and down by ~10% so the results are within a 10% error margin.  I don't see a difference between static and dynamic tiles at all.

**Comment by moufmouf** [comment]
Test 3: Same commit, static layers, but we skip creating a layer for "functional layers" (like entry, exit, jitsi, etc...)

![image](https://user-images.githubusercontent.com/1290952/102821209-fb1d5d00-43d6-11eb-99f5-a680cc314f3e.png)

Result: it does not make much difference.

**Comment by Palid** [comment]
@moufmouf did the profiler yield similar results? Checking only CPU usage without actual calls chart isn't that valuable of a metric due to JIT and other optimisations under the hood.

**Comment by moufmouf** [comment]
Hey @Palid ,

thanks for the tips. Actually, I did not have a look at the calls chart.
What I'm interested in is lowering the CPU usage globally. I'm looking to find a way to reduce energy consumption (important if you are using a laptop on battery) and CPU/GPU usage was a good candidate for this.
But indeed, since the changes I do do not seem to impact CPU/GPU usage at a measurable level, I'll probably need better tools.
I'm not sure a typical call chart would help me much though... Actually, if anyone has an idea on how to measure this properly, I'm all ears.

**Comment by Palid** [comment]
Well, we'd probably need to define a baseline for tests first. We probably should do performance testing for  1person, 10people, 50people and 100 people on the instance to verify actual performance hit. I can probably help you out with that. :)On Dec 22, 2020 22:52, David Négrier <notifications@github.com> wrote:
Hey @Palid ,
thanks for the tips. Actually, I did not have a look at the calls chart.
What I'm interested in is lowering the CPU usage globally. I'm looking to find a way to reduce energy consumption (important if you are using a laptop on battery) and CPU/GPU usage was a good candidate for this.
But indeed, since the changes I do do not seem to impact CPU/GPU usage at a measurable level, I'll probably need better tools.
I'm not sure a typical call chart would help me much though... Actually, if anyone has an idea on how to measure this properly, I'm all ears.
