### ISSUE TITLE
IFRAMEs fail to trigger beforeunload events on closing

### ISSUE THREAD

**Issue by dronus** [thecodingmachine/workadventure#516]
When leaving an URL location on the map, the current iframe is hidden. At this point, its documents beforeunload event is not fired. When attending the same map location again, the URL is loaded again, so the old page is not accessable anymore. Still no beforeunload fired. Does this mean the pages never unload and old iframes are still lingering around? Or are the events prevented somehow?

This is a little bit problematic, as URL locations presenting forms or some kind of whiteboards or other things that allow work to do but need be confirmed or saved explicitely will loose all work done if the avatar just walks away!

**Comment by moufmouf** [comment]
Indeed, I never considered this problem previously.

The problem seems to be that we cannot detect from within WorkAdventure if a "unbeforeunload" event is triggered or not in an iFrame (see: https://stackoverflow.com/questions/49445671/how-to-trigger-beforeunload-event-from-within-an-iframe)
So we have no way to hide the iFrame **after** the modal was shown asking to save explicitly the content.

Maybe we could consider adding a property in WorkAdventure maps for iFrames to behave differently, but even though, I'm not sure what the correct behaviour could be.

**Comment by gparant** [comment]
Hi, today we can close a iframe and continue the moving on WorkAdventure.

I close this issue and we still available if you have any other question.
Thanks for your feedback 💪

**Comment by dronus** [comment]
The problem was not to close the IFRAMEs (which already worked), but how to handle "beforeunload" handlers of the IFRAMEs document!

Basically just closing them without invoking the handler may lead to data loss on some web pages (forms not completed).   Best behaviour would be to keep the IFRAME but hidden until those handlers complete. It is however hard to tell from the outside when that happened.
