### ISSUE TITLE
Feature request: embedded IFRAMEs 

### ISSUE THREAD

**Issue by dronus** [thecodingmachine/workadventure#517]
Would be cool if iframes could be embedded in the map directly, eg. have some iframe that just takes place of the tiles marking its URL location. This would allow for simple dashboards, show small movies or enable other kind of interactions directly in the map without interrupting the flow by opening a large frame.

**Comment by moufmouf** [comment]
This is probably trickier than it sounds, but now that we know that Phaser supports HTML objects, maybe we could consider that?

@Kharhamel , you have played quite a lot with HTML objects in Phaser. Do you think it is possible?

(that would also be super useful to directly display a live stream on a screen in a virtual theater :open_mouth:

**Comment by Kharhamel** [comment]
Iframes are not listed in the phaser3 example repository: https://github.com/photonstorm/phaser3-examples/tree/master/public/src/game%20objects/dom%20element , so I cannot guarantee that it will work.

I guess that it should work but I have no idea about the performance.
If it does run well, then allowing an "openUrlInIframe" property in maps would be pretty cool. For interactions though, we probably won't allow much. There is no way we let map makes write javascrcipt that will be run into the game, it is just to insecure.

I am planning on testing iframe in dom elements anyway, because the actual iframe is too clunky to use. I'll update this issue if I find some interesting stuff.

**Comment by GRL78** [comment]
Now possible and explain here : https://workadventu.re/map-building/website-in-map.md
