### ISSUE TITLE
Local Setup Issues

### ISSUE THREAD

**Issue by CodeFreezr** [thecodingmachine/workadventure#536]
First things first: Thx for that awesome cyber-stuff!

I've try to setup a local workadventure via docker-compose & WSL2.

**First Steps:**

1. Adding workadventure.localhost to /windows/system32/drivers/etc/host
2. reboot
3. git clone ... 
4. docker-compose up

**Prob1:**
All browsers I tried (FF, Chrome, Edge, Opera) fail on a 404 Could not load map (**http**://npeguin.github.io/office-map/map.json). Perhaps https vs. http Issue?

**Steps in FF:**
1. Change Firefox Setting to HTTPS-Only for all ...
2. 404 are gone, login possible, Click on "Try it Now!", Press Enter to Start
3. The map shows for one Second (hurray!)

**Prob2:**
After 1-2 Seconds a "Connection Lost Reconnecting ..." Screen will show forever.

I found some suspicious messages in the console (See Screenshot). But I can't figure it out yet.
Perhaps I oversee a small simple configuration? 

![2021-01-02 19_39_03-Window](https://user-images.githubusercontent.com/966869/103464292-d27c5800-4d32-11eb-8412-e7741d5db9ff.jpg)

**Comment by CodeFreezr** [comment]
I tried something more:

1. create map
2. select the upper left one
3. click "start"

Prob 3:

- After some "self-signed-risk" Warnings, prob. because of **https**://play.workadventure.localhost/_/lxb-olx-mrn/npeguin.github.io/skapa-map/map.json
- I finally crashed on this 404 (invalid url) /_/rfc-lyr-iym/npeguin.github.io/office-map/map.json

**Comment by djmaze** [comment]
@CodeFreezr Did you try requesting each subdomain via https once, as shown [in this issue](https://github.com/thecodingmachine/workadventure/issues/452#issuecomment-732814375)? That resolved it for me.

**Comment by CodeFreezr** [comment]
Jup, "accept the risk" on all four with FF


https://workadventure.localhost/ - Startpage ok, click on "Try this out" -> 404 for "/_/global/npeguin.github.io/office-map/map.json"
https://play.workadventure.localhost/ -> Invalid Url "/"
https://maps.workadventure.localhost/ -> Forbidden 
https://api.workadventure.localhost/ -> Bad Gateway

**Comment by djmaze** [comment]
`develop` works for me.

**Comment by P1tt187** [comment]
I face the same problems on windows, linux. looks like #538 fixes the cert issues on local setup.
I also got the 404 error even with this fix. In the Console the error is shown that  `'Access-Control-Allow-Origin'` is missing.
The error is also shown in https://github.com/thecodingmachine/workadventure/issues/536#issuecomment-753511643 (CORS REQUEST).

How can we set the Header?

**Comment by djmaze** [comment]
Looks to me like you have a wrong map url. At least the one shown in the screenshot has the additional prefix `/rfc-lyr-iym` which needs to be removed.

On another note, I found a way to save us from the complete TLS / certificate hassle in development. Just make the following change and you can use http://workadventure.localhost again (at least when working with the sample maps):

```diff
diff --git a/front/src/Connexion/Room.ts b/front/src/Connexion/Room.ts
index 5cd2604..9e6d1dc 100644
--- a/front/src/Connexion/Room.ts
+++ b/front/src/Connexion/Room.ts
@@ -55,7 +55,7 @@ export class Room {
             if (this.isPublic) {
                 const match = /_\/[^/]+\/(.+)/.exec(this.id);
                 if (!match) throw new Error('Could not extract url from "'+this.id+'"');
-                this.mapUrl = window.location.protocol+'//'+match[1];
+                this.mapUrl = 'https://'+match[1];
                 resolve(this.mapUrl);
                 return;
             } else {
```

**Comment by CodeFreezr** [comment]
Should I have to build stuff before docker-compose build -d?

**Comment by djmaze** [comment]
You mean before `docker-compose up`? No, everything will be recompiled automatically.

**Comment by do5rsw** [comment]
I was abble to move around all that CORS issues on my local instance by using the Moesif Origin Plugin in Chrome on Linux.
Still I can access the main page but the e.g. "try it out now" link gives me a 404 in the browser. 
The developer tools report no more CORS issues now but I keep getting 502 Bad Gateway from pusher.woradventure.localhost when the site trys to POST access http://pusher.workadventure.localhost/anonymLogin .
This is the only error that is now reported but it seems to be enough to keep it not working. 
Any tips why this occurs?

**Comment by do5rsw** [comment]
I'd recommend the developers to check for CORS for this is nothing with certificates but with accessing one subdomain from annother (i.e. origin issures) and it happens in FF aswell as chromium and chrome. As said in chrome it can be worked around be using the Moesif plugin to rewrite the corresponding headers with the correct values.

**Comment by do5rsw** [comment]
Ok I can give an update:

I got it to work now. 
If you use the default domain workadventure.localhost it will only work out of the box if you 
- create entries for the subdomains in your /etc/hosts file (or DNS - whatever you have)
- then start docker-compose up
- use chrome with moesif plugin. In moesif enable advanced features
- in moesif advanced settings set origin and access-control-allowd-orign to https://play.workadventure.localhost 
- in moesif advanced settings set access-control-allow-credentials to true
- save these settings 
- then open https://workadventure.localhost and all other subdomains once in chrome and accept the security warning on each
- then open https://workadventure.localhost and click on one of the buttons and see it working :)

This is mainly due to CORS blocking access to various pages due to non matching origin or missing headers which again seems to be maily due to not using an existing domain name. Additionally there is the already mentioned self-signed-cert whoes.
Btw: the self signed certs are regenerated everytime you restart your docker container so you would have to repeat the 7th step after every restart of docker-compose again.

The subdomains you need are the following:

workadventure.localhost
play.workadventure.localhost
pusher.workadventure.localhost
maps.workadventure.localhost
api.workadventure.localhost
uploader.workadventure.localhost

in a local thesting env like on my laptop here they should all resolve to 127.0.0.1.
the startoage http(s)://workadventure.localhost will work even without the hosts/dns entries because traefijk binds to 0.0.0.0:8080 -. i.e. it listens on all interfaces that are there but missing dns/hosts entries were indeed the reason why I kept getting 502 bad gateway from pusher (that is the loadblancer).

With all of these I got it to work in chrome. It will not work in http because play.workadventure.localhost always accesses mapfiles from the web via https (even if itself is called via http) which causes a constellation that again triggers a CORS block.

HTH

**Comment by P1tt187** [comment]
the description from @do5rsw works for me, thx.
I think it would be better to provide trafik a local self signed wildcard certificate which is added to the truststore.
This would avoid calling the subdomains manually.

**Comment by do5rsw** [comment]
@Ptt187 yes maybe. For local testing purposes I'm fairly ok with my solution. If you use it on "productive" environment I'd also recommend using an existing real (sub)domain plus the mentionend (sub)subdomains and a valid and trusted ssl certificate instead of local domain and autogenerated selfsigned certificate.

**Comment by do5rsw** [comment]
btw it also works in Firefox if you use e.g. the CORS Everywhere plugin which does rather the same as the moesif plugin in chrome does. Just I noticed that here it did run more smoothely in chrome than in firefox ;)

**Comment by do5rsw** [comment]
@Ptt187 if you have traefik with a valid wildcard cert could you please do us the favour and check if workadventure.localhost will then work even without the CORS plugins?

**Comment by do5rsw** [comment]
BTW: caveat: keep in mind that you disable your CORS plugin when you don't needed. Otherwise it will keep other sites from working ;)
You could also try - at least moesif in chrome has one - to make a whitelist of domains where the plugin should work  - to avoid this!

just forgot to mention that prior. Without whitelist filled or no whitelist (CORS everywhere) the plugin will rewrite EVERY cors header of every page ;)

**Comment by CodeFreezr** [comment]
Could we CORS-Issues generally avoid if we put all the service in one domain?

For e.g. instead of 

workadventure.localhost
play.workadventure.localhost
pusher.workadventure.localhost
maps.workadventure.localhost
api.workadventure.localhost
uploader.workadventure.localhost

why not configure:

workadventure.localhost
workadventure.localhost/play
workadventure.localhost/pusher
workadventure.localhost/maps
workadventure.localhost/api
workadventure.localhost/uploader

Then it would be possible to call stuff criss-cross without even think about CORS.

**Comment by djmaze** [comment]
That would make it harder to scale.

It would be best if this was configurable.

**Comment by CodeFreezr** [comment]
> 
> 
> Looks to me like you have a wrong map url. At least the one shown in the screenshot has the additional prefix `/rfc-lyr-iym` which needs to be removed.
> 
> On another note, I found a way to save us from the complete TLS / certificate hassle in development. Just make the following change and you can use http://workadventure.localhost again (at least when working with the sample maps):
> 
> ```diff
> diff --git a/front/src/Connexion/Room.ts b/front/src/Connexion/Room.ts
> index 5cd2604..9e6d1dc 100644
> --- a/front/src/Connexion/Room.ts
> +++ b/front/src/Connexion/Room.ts
> @@ -55,7 +55,7 @@ export class Room {
>              if (this.isPublic) {
>                  const match = /_\/[^/]+\/(.+)/.exec(this.id);
>                  if (!match) throw new Error('Could not extract url from "'+this.id+'"');
> -                this.mapUrl = window.location.protocol+'//'+match[1];
> +                this.mapUrl = 'https://'+match[1];
>                  resolve(this.mapUrl);
>                  return;
>              } else {
> ```

Yes finaly this oneliner works after Accepting all six "https-risks" domains.

**Comment by CodeFreezr** [comment]
> 
> 
> That would make it harder to scale.
> 
> It would be best if this was configurable.

Why should this be a problem on scaling? Normally Loadbalancer could have Path-Based rules.

**Comment by moufmouf** [comment]
Hey @djmaze ,

Thanks for the one-liner here: https://github.com/thecodingmachine/workadventure/issues/536#issuecomment-753682769

I opened an issue (#569) to definitely fix the problem.

**Comment by djmaze** [comment]
@CodeFreezr 

> Why should this be a problem on scaling? Normally Loadbalancer could have Path-Based rules.

Because with subdomains you can separate via DNS / IP, thus allowing to use a completely independent infrastructure. But I agree, that should probably not make much of a difference in practice.

**Comment by CodeFreezr** [comment]
1000thx to helping here for my local-setup issues. I think this one could be closed, perhaps a reference for a FAQ later on.
