### ISSUE TITLE
Allow displaying proper licence attribution for tilesets

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#568]
A lot of tiles are released under the Creative Commons Attribution-ShareAlike license.
This license requires to properly "credit" the author.

So far, there isn't any way to easily to this (except in a text file next to the map on Github).

We could plan to read a new special property that we put on each tileset of each map.
The property could be named "licence" and contain some text with proper attribution.

This information could then easily be displayed in a "credits" section inside WorkAdventure or on the WorkAdventure website.

**Comment by basxto** [comment]
*(since it makes more sense to writhe this here than in an email)*
It would be best if it was MarkDown or a similar simple format, where you can link authors, licenses and sources.
https://wiki.creativecommons.org/wiki/Best_practices_for_attribution

There should be plenty of MarkDown renderers available in JavaScript.
A file like `ATTRIBUTION.md` also could be easily viewed on github/gitlab/gitea, I think that’s somewhat relevant for the templates.
In the worst case MarkDown can be read in plain text.

**Comment by fkohrt** [comment]
In order to make attribution easier, you could also implement fields for title, author, author link, license, source and a custom string. License could be a [SPDX identifier](https://spdx.org/licenses/). The interface could then take care of assembling the actual statement with the custom string appended.

**Comment by lunar-debian** [comment]
With experiences like rc3 in mind where many participants made their own maps, I believe it would be better to have attributions be defined in the map and have them available in the menu inside the game.

**Comment by basxto** [comment]
> With experiences like rc3 in mind where many participants made their own maps, I believe it would be better to have attributions be defined in the map and have them available in the menu inside the game.

rc3 allowed to have a COPYRIGHT file at the root of each git repository

**Comment by tabascoeye** [comment]
the Button which #rc3 implemented for this looked roughly like this:
https://github.com/tabascoeye/workadventure/commit/7b7c695f76ff8db095ab6b888f2039d3c7bbad35

placement of the button (especially on smaller/mobile screens) is highly questionable though…

**Comment by GRL78** [comment]
There is property for copyright on a map and tilesets. If those properties are used the copyright will be displayed in the menu.
