### ISSUE TITLE
Move character using the mouse

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#595]
We could use a A* algorithm (shortest path finding on a map) to let a character move by a click on the screen.
This could be useful for mobile devices that are not currently supported.
We could have support for mobile without having to add a virtual joystick (that could be useful since the screen will already be filled on mobile with videos + the game itself).

There is a JS library implementing the A* algorithm out of the box! https://easystarjs.com/

Related to #575 and #402

**Comment by lunar-debian** [comment]
I kinda paused after reading this because this could affect the user experience quite a bit. What made my experience with WorkAdventure so different from other virtual meeting software is that it felt spatial. I had to “walk” from one place to another. Pushing the arrow keys to move my character from one place to another made me feel like I was moving. I really wonder if a series of click would make me feel the same. What do you think?

(I totally understand the thrill to implement A* in the game, though…)

Happy to discuss this further if you stumble on my avatar on floor0.

**Comment by Grosskopf** [comment]
> Pushing the arrow keys to move my character from one place to another made me feel like I was moving. I really wonder if a series of click would make me feel the same. What do you think?

it could be implemented in a number of ways:

- Clicking and letting the character walk there while not instantly being there like in point and click adventures
- Pressing and holding the left mousebutton somewhere to make the character move there, once you let go of the mouse, the character stops
- Creating a virtual d-pad for touch input

What do you think about these alternatives?

**Comment by nolway** [comment]
Currently available.
