### ISSUE TITLE
What should workadventure.mydomain.com show?

### ISSUE THREAD

**Issue by z3ky** [thecodingmachine/workadventure#635]
Hi,
I've just setup up workadventure on my server and https://play.workadventure.mydomain.com works fine. In the docker compose file I changed all workadventure.localhost to workadventure.mydomain.com and configured ssl with traefik/dynamic_conf and my certificates. However, workadventure.mydomain.com still returns 404 page not found. What is that url supposed to show?

**Comment by tabascoeye** [comment]
it used to show the contents of container "website" which is essentially what you see when visiting http://workadventu.re
Since it makes sense to separate the website describing WA from the instances, TCM deleted the container "website" from this repo.
So I guess the "no subdomain" domain is pointing to nowhere at the moment. Should likely either redirect to play.* or fully replace play.* imhi

**Comment by atomheartother** [comment]
This also happens on a local install, unlike what the readme says, `workadventure.localhost` returns a 404 page. `play.workadventure.localhost` works though.

**Comment by z3ky** [comment]
The readme is why I'm asking. But using the url for the website was apparently too obvious to me :D Thanks!

**Comment by gparant** [comment]
I close this issue. We still available if you have any question.

Thanks for your feedback 💪
