### ISSUE TITLE
after install page not found 404

### ISSUE THREAD

**Issue by 4clu** [thecodingmachine/workadventure#650]
hi all,

i've been trying to install the master:branch to workadventure for some time now. but i always get `page not found 404` on
play.workadventure.localhost workadventure.localhost

my preparations:
`apt update && upgrade `

`apt install curl wget ufw apache2 certbot python-certbot-apache docker docker-compose nodejs npm nano`

`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list`

`apt update`
`apt install yarn`

`cd /home`
`git clone -b master --single-branch https://github.com/thecodingmachine/workadventure.git`

`cd workadventure/`
`docker-compose up`
(or `docker-compose -f docker-compose.yaml up -d`)

after `docker-compose ps` and `docker ps` all containers are running but i get on my `play.workadventure.localhost` and `workadventure.localhost` `page not found 404`

**Comment by axelirriger** [comment]
That wont work. Try to open/load http://play.workadventure.localhost - at least for me that did the trick.

**Comment by 4clu** [comment]
hi axelirriger,

thank you for your comment. i try to open and load the site in different browser (firefox, chromium) but nothing is happened. 
`docker-compose logs front` say nothing, that something is wrong. 

maybe the problem is that my server is a vserver? oh, and ir run `ubuntu 18.04 tls `!

Is it still necessary to make settings in /etc/hosts (e.g. 127.0.0.1 workadventure.localhost)?

**Comment by axelirriger** [comment]
Hi 4clu,

I tested the setup on my macbook with vagrant (which essentially fires up a linux box).
When you "docker-compose up" stuff, a virtual network is created and alle containers are connected with each other. That solves the inter-container communication. For the external access you have to edit /etc/hosts to map workadventure.localhost to 127.0.0.1 (or whatever IP is right for you). You need that, because the browser tries to access api.workadventure.localhost and play.workadvanture.localhost.

If workadventure is installed on a vServer and you want to access it from the outside, more configuration is necessary so that each container uses and knows to correct host names - but for a "quick" test from localhost, accessing containers on the same host, that should do.

If that does not help, what about firefox or chromium web developer console and especially the network view. There you should be able to see what is accessed and how that behaves (not).

**Comment by 4clu** [comment]
oh wow, thank you for testing my configuration!!!

you mean, 

> If workadventure is installed on a vServer and you want to access it from the outside, more configuration is necessary so that 
each container uses and knows to correct host names

do you have a idea where I can make these settings and what they are?

**Comment by 4clu** [comment]
oh i feel me lost, 

have someone help for a recommended install on debian-based system with singel-domain? what can i do to run an a singel-domain, how to set up ssl/tls, set up correcly jitsi ... what must i learn for running workadventure (okay, docker ..)?

maybe a short step by step guide can reduce q-and-a's in the issues'forum' for the installation-progress!?

i would really like to ask knowledge holders again to break down barriers (e.g. installation, configuration of wa) and provide a great experience for all people during lockdown and create a great community :-)

thank you <3

**Comment by gparant** [comment]
I close this issue. We still available if you have any question.

Thanks for your feedback 💪
