### ISSUE TITLE
How to run Workadventure dockers on a remote server?

### ISSUE THREAD

**Issue by klausagnoletti** [thecodingmachine/workadventure#665]
Hi

How do I run workadventure on a non-local machine? For instance on my Xeon-based Docker server.  Is a description of how to do that available somewhere? How does it work with domain names and DNS? What needs to be set up?

Thanks

/k

**Comment by tabascoeye** [comment]
on the main branches (master and develop) there is no simple solution ready yet.
Some pull requests are pending which clean up the docker files and propose a "prod" file for production use.
PRs #576 #577 and #578 show some of that effort.
I'm using those and other changes on my fork and they work pretty well.

tl;dr: you have to invest some work or wait for WA devs to get a production docker compose file ready

**Comment by klausagnoletti** [comment]
Allright. Thanks. I have to little knowledge of Traefik and too little overview of the project in general to help out right away. I'll see what I'll do.

**Comment by Kharhamel** [comment]
See theses issues: #738 and #794. 
We really want to finish an official documentation on self-hosting because this subject is starting to be asked a lot.
I have next sprint (in 2 weeks) will be about that.
I am closing this issue, but if you still need help, you can always comment in theses other issues, or come ask questions in our discord in the section 'self-hosting'.

**Comment by florinvirdol** [comment]
@Kharhamel  did you finish any official documentation about self-hosting? 
Thank you!
