### ISSUE TITLE
World name is not updated through WorkAdventure URL

### ISSUE THREAD

**Issue by Deathtroy** [thecodingmachine/workadventure#712]
Hello, I tried to update the world name into my account, it display the new name but the pattern in the URL is not changed, even if I delete all the rooms and deactivate the instance of the world and then create a new room.

![image](https://user-images.githubusercontent.com/18733773/107249245-2bf63780-6a01-11eb-899c-77eef47141b3.png)

**Comment by gparant** [comment]
Hi, it's too dangerous to update the world name URL because if you process sending email with the current URL, and changes it after update world name, when people trying to connect to our URL, an error message will display.

The solution is to close your world and make a new world with the correct name and have the same name in the URL.

We might image in the future, develop a checkout mode to force or update your world's URL.

Thanks for your feedback 💪
