### ISSUE TITLE
Avoid interrupts on deploy

### ISSUE THREAD

**Issue by jessedobbelaere** [thecodingmachine/workadventure#715]
Is the recommendation to run multiple API and Pusher pods at the moment or only 1 of each? I guess there's a need for sticky loadbalancing to make that work, as I saw https://github.com/thecodingmachine/workadventure/issues/404 mention redis as a store? 

I'm trying to avoid downtime when a deploy is happening, as it currently interrupts me and some friends in a room. For the frontend pod, a `startupProbe` can be used to avoid sending traffic while webpack is still running until [precompilation is added](https://github.com/thecodingmachine/workadventure/pull/577), but the single pusher and back service still gets killed ofcourse at some point with a rolling update.

**Comment by moufmouf** [comment]
Hey @jessedobbelaere ,

We have no easy solution for this right now. We cannot really do rolling upgrades since API is stateful and we don't have short term plans to use Redis.
Also, you will need to refresh WA anyway if the front pod is modified anyway.

So the only solution we have right now is to upgrade in the middle of the night.
In the future, we might try rolling upgrades: when a room a closed, it starts again on a new API server. But don't expect this too soon :s

**Comment by jessedobbelaere** [comment]
Yeah sounds like a tricky thing to tackle indeed! Thanks for clarifying this, I thought I missed something in the source code. And thank you for this great platform!
