### ISSUE TITLE
Stripes between tiles

### ISSUE THREAD

**Issue by eazyliving** [thecodingmachine/workadventure#766]
Hiho,

somewhere after rc3 I noticed stripes between tiles appearing.

![image](https://user-images.githubusercontent.com/3582086/108633016-3ccb9200-7472-11eb-860d-9bd63e4ece77.png)![image](https://user-images.githubusercontent.com/3582086/108633025-4228dc80-7472-11eb-80fc-c9a99eb15e14.png)

Stripes appeare/disappear while walking.

This was not the case some weeks ago when I started testing my first maps at play.workadventu.re.
Older / different builds (like play.wa.binary-kitchen.de) do not show that stripes.

**Comment by eazyliving** [comment]
Need to add the information, that this occurs in combination with running (shift-key)

**Comment by davidhuberff** [comment]
Same Issue here. It occurs when going (or running) up or down, but not when going (or running) left or right)
![image](https://user-images.githubusercontent.com/77616559/108968318-eaac8b80-7680-11eb-8150-6093013528b5.png)

**Comment by moufmouf** [comment]
Hey guys, can you send me URLs to maps that have the issue?

Are you using the Workadventure map starter kit (https://github.com/thecodingmachine/workadventure-map-starter-kit)
It comes with a "build process" that modifies the tiles on the fly. Modified tiles are normally "extruded" to avoid this effect.

**Comment by davidhuberff** [comment]
Hi, thats the URL to our (test) workadvenute: 

https://play.test01.vime.nextfarming.dev/_/global/maps.nextfarming.dev/Test-01/json/ig14.json

**Comment by eazyliving** [comment]
Hiho,

my map can be found here:

https://fyyd.de/fyydiverse/fyyd.json

Stripes occur with the workadventu.re server and of course my own:
https://play.wa.fyyd.de/ or https://play.workadventu.re/_/global/fyyd.de/fyydiverse/fyyd.json

They do not occur with an older version like the one in the binary kitchen:
https://play.wa.binary-kitchen.de/_/global/fyyd.de/fyydiverse/fyyd.json

And @davidhuberff is correct, it happens while walking/running vertically.

**Comment by plan5** [comment]
I experience the same issue with this map: https://raw.githubusercontent.com/plan5/plan5.github.io/main/Platz.json

It wasn't there some weeks ago.
And I think it happened at the same time that the deploy script stopped working for me (tiles were shuffled after deploying) so I started serving my maps directly from the repo instead of github pages.

One thing that is possibly relevant: 
These tiles were scaled from 16x16 to 32x32. So the gap between tiles is 2px.

**Comment by eazyliving** [comment]
Interesting. My tilesets are all without space except for two with space and margin.

Your fixed version doesn't work, it misses smth.

I could change all my tilesets to a spacing of 1, but... well... it worked until... it didn't work anymore :D

**Comment by plan5** [comment]
Ah, in your first screenshot it seemed to me that the left half texture has half the resolution of the rest (guessed by smallest dot size). And since the right side seems to have no stripes I thought for you it's scaled tilesets as well.

The fixed version is...fixed now :) And here is the one generated by the deploy script
https://play.workadventu.re/_/global/plan5.github.io/Platz-fixed.json
Still has stripes but much less.

**Comment by plan5** [comment]
#819 could be related

**Comment by buenni86** [comment]
It is because of the phaserMode.
With CANVAS you don't have those stripes.

Here the broken one with canvas:
https://play.workadventu.re/_/global/raw.githubusercontent.com/plan5/plan5.github.io/main/Platz_broken.json?phaserMode=canvas

with auto or webgl you have those stripes.

**Comment by GRL78** [comment]
To not have this issue use the starterKit : https://github.com/thecodingmachine/workadventure-map-starter-kit
