### ISSUE TITLE
Help with Nginx as proxy

### ISSUE THREAD

**Issue by saschafoerster** [thecodingmachine/workadventure#815]
I would like to install WorkAdventure on a running server, next to Jitsi and BigBlueButton. Because some services are already running on this machine, Nginx is set as the proxy for all 80/443 traffic. I tried to install all the different docker-compose for production and for development, even some dockers on the interwebs, but I never got a fully working adventure. I never used traefic, so I do not really understand, what configuration is needed. Sometimes I could see the website DOMAIN, but noch play.DOMAIN. So I tried other configurations with a single domain, it never worked out. Hours wasted, when it should be simple: docker-compose up. 

Actually, I wish it wasn't so difficult to try out WorkAdventure on your own server with an existing proxy, a single domain and a single (already existing) certificate.

So the question: did someone succeed in installing it next to nginx and would share his yml and .env files? :)

**Comment by Lurkars** [comment]
Hello, I have successfully single domain deployment with Apache as proxy, should work same with using Nginx. 

Because of single domain deployment, there are many changes, but if that is not required, can be ignored. The important part for me is the traefik config and disabling SSL completely. In traefik those two things were the important change for me. I do not use any other port than port 80 and make it under different port available
`
- --entryPoints.web.address=:80
ports:
      - 9999:80
`
The port 9999 can be replaced by whatever you want, and then I used Apache for proxy to localhost:9999

Here is my full docker compose, this is productive mode with images, but proxy config also worked with dev-setup for me.
[docker.compose.yaml.txt](https://github.com/thecodingmachine/workadventure/files/6159700/docker.compose.yaml.txt)

**Comment by saschafoerster** [comment]
@Lurkars Thank you very much! :) Now the map-building can start! 😇

**Comment by saschafoerster** [comment]
I tried to continue using your docker-compose.file in the newest release 1.2.0, but I am not able to create a working instance. 
`git checkout v1.1.0` > everything works
`git checkout v1.2.0` > "docker-compose up"

1. first I have to add in "front:" to create a working instance
`STARTUP_COMMAND_1: ./templater.sh`
2. error appears then in my browser console (I replaced my domain with URL)
`sockjs.js:1606 GET https://URL:80/sockjs-node/info?t=1618004135122 net::ERR_SSL_PROTOCOL_ERROR`
I saw that between release 1.1.0 and 1.2.0 this file has been changed and introduced the hard coded port 80: 
https://github.com/thecodingmachine/workadventure/blob/a1f06ffbd58390207772f45e5f31c7234f1f821d/front/webpack.config.js#L15
So I switch it manually to :443
`sockPort: 443,`
Then I get a new error message in the browser console, when two avatars are standing next to each other:
```
VideoPeer.ts:204 pushVideoToRemoteUser => 2 TypeError: Cannot read property 'addTrack' of undefined
    at VideoPeer.addTrack (index.js:292)
    at VideoPeer.pushVideoToRemoteUser (VideoPeer.ts:201)
    at new VideoPeer (VideoPeer.ts:108)
    at SimplePeer.createPeerConnection (SimplePeer.ts:150)
    at SimplePeer.receiveWebrtcStart (SimplePeer.ts:112)
    at SimplePeer.ts:89
    at RoomConnection.ts:427
    at RoomConnection.dispatch (RoomConnection.ts:205)
    at WebSocket.RoomConnection.socket.onmessage (RoomConnection.ts:173)
```
Did someone else succeed in creating a working single domain instance behind Nginx for "small productions"?

**Comment by saschafoerster** [comment]
@moufmouf By the way: is there a reason (I just don't know), why you don't recommend running WorkAdventure behind nginx with a single domain in production?

**Comment by JonnyTischbein** [comment]
Thanks for your tipp with sockPort `workadventure/front/webpack.config.js` !

I did get work adventure to run behind an apache as reverse proxy but with multi domain setup.

Therefore I adjusted the exposed docker ports of traefik (the 443 port is not in unsed and could be disabled too):
```
  version: "3"
  services:
    reverse-proxy:
      image: traefik:v2.0
      command:
        - --api.insecure=true
        - --providers.docker
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443
      ports:
        - "6180:80"
        - "6143:443"
        # The Web UI (enabled by --api.insecure=true)
        - "6186:8080"
     [...]
```

I replaced every domain in the docker-compose file with my domain, so I'm running `play.my.domain.com` and `maps.my.domain.com` and so on.

In my apache config is reverse for `my.domain.com` and all sub(sub)domain with `*.my.domain.com` and redirect all request to the traefik docker container. Also note the ws upgrade redirection.

```
<VirtualHost *:80>
	ServerName my.domain.com
        ServerAlias *.my.domain.com
	
	RewriteEngine On
	RewriteCond %{HTTPS} off
        RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L] 
</VirtualHost>
<VirtualHost *:443>
	ServerName my.domain.com
        ServerAlias *.my.domain.com

        SSLEngine on
        # LETS ENCRYPT SSL Certificate file
        SSLCertificateFile      /etc/letsencrypt/live/my.domain.com/fullchain.pem
        SSLCertificateKeyFile   /etc/letsencrypt/live/my.domain.com/privkey.pem

	ErrorLog ${APACHE_LOG_DIR}/workadventure-error.log
	CustomLog ${APACHE_LOG_DIR}/workadventure-access.log vhost_combined

        DocumentRoot /var/www/
       
        SSLProxyEngine on

        ProxyPreserveHost On
        RequestHeader set X-Forwarded-Proto "https"

        ProxyPass        / http://localhost:6180/
        ProxyPassReverse / http://localhost:6180/

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule ^/?(.*) "ws://localhost:6180/$1" [P,L]
</VirtualHost>
```
And now the important part thanks to your comment.
I changed the sockjs Port to 443, to enable routing through the reverse proxy. (Otherwise it will fail with an request like https://play.my.domain.com:8080/sockjs-node/info?t=123456 and my apache listens on 443)

Just add the `sockPort: 443, ` here.

```
#### ./front/webpack.config.js
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
    entry: './src/index.ts',
    devtool: 'inline-source-map',
    devServer: {
        contentBase: './dist',
        host: '0.0.0.0',
        sockPort: 443,

```

Since now I did not had the chance to stress test it, but looking at my server and grafana stats it looks all good. I don't see any reason why not using a reverse proxy in front.
E.g. for Jitsi (which also uses websockets now) I also use apache as an reverse proxy.

If wanted I could also create an wiki / documentation README text, if that is wanted ?

**Comment by Wikinaut** [comment]
Info only: the xce-Fork has a working setup for single-domain.
https://github.com/workadventure-xce/workadventure-xce/blob/xce/contrib/docker/docker-compose.prod.singledomain.yaml

**Comment by JonnyTischbein** [comment]
But according to your link docker-compose file it is not explicit for running behind a reverse proxy, because it exposes the ports on 80 and 443.
Do you know, if they covered this use case ?

**Comment by Wikinaut** [comment]
Pls. contact these experts - I am not an expert.

**Comment by klassiker** [comment]
I'm running a single-domain setup without docker behind an nginx. 

@saschafoerster The error `TypeError: Cannot read property 'addTrack' of undefined` is triggered because there is no peer-connection. See this line: https://github.com/feross/simple-peer/blob/master/index.js#L304

`this._pc` is most likely not set because your `iceServers` (STUN/TURN) are not parsed correctly by the browser. This could be caused by not setting `TURN_USER``/TURN_PASS` or using the `TURN_STATIC_AUTH_SECRET`. See this line, the error is always catched and then results in problems elsewhere: https://github.com/feross/simple-peer/blob/master/index.js#L101

**Comment by saschafoerster** [comment]
@klassiker First I couldn't believe, as my STUN/TURN-configuration did work with version 1.1.0. After a lot of trials and errors the solution was this: I added the "TURN_STATIC_AUTH_SECRET" in the back-container, as a already have a different TURN-server running. After that change, the develop-version was running! :) Thanks everyone for this help and guiding me! 

```
  back:
...
      TURN_STATIC_AUTH_SECRET: "${TURN_STATIC_AUTH_SECRET}"
```

**Comment by Oyabi** [comment]
@saschafoerster Hello, I'm experiencing the same issue as you, but I haven't been able to resolve it yet. Could you please share your complete configuration with me? This includes both the docker-compose.yml file and the nginx configuration. Thank you!
