### ISSUE TITLE
Frame handles may overlay action buttons of their embedded websites and make them unreachable

### ISSUE THREAD

**Issue by Wikinaut** [thecodingmachine/workadventure#850]
![grafik](https://user-images.githubusercontent.com/1151915/112718121-40c75580-8ef1-11eb-8fa2-5345cba3f7e3.png)

**Comment by tabascoeye** [comment]
Now that there is a pretty thick "bar" which is there to make the "coWebsite" resizeable, I would propose to put both the "close" button as well as the "resize half-half" button ON that bar. That way they can be visible all times AND not obstruct any part of the website displayed.
Also: please change the icon of the "resize to half-half" button. The icon suggests some "sharing" function instead of what it actually does

**Comment by tabascoeye** [comment]
<img width="459" alt="Screenshot 2021-03-29 at 12 09 40" src="https://user-images.githubusercontent.com/111893/112822038-b2d1a300-9087-11eb-86f4-e47a896a79c0.png">

Something like this?

**Comment by Wikinaut** [comment]
why not putting the handles on top (north)?

**Comment by Wikinaut** [comment]
The audio slider should be moved a little bit.

**Comment by Kharhamel** [comment]
This is a good idea, I will do it when I have a moment
