### ISSUE TITLE
Allow multiple start positions

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#96]
A map does not have only one start position. Actually, it has many (if I go to TCM first floor and go back to floor0, I expect to arrive down the stairs, not next to the entrance door)

So we should probably have more than one possible "start layer" (using properties rather than name)
An exit url could reference a start layer using the # notation (this is really similar to an anchor in HTML)

For instance:

```
floor0.json#downthestairs
```

**Comment by gulien** [comment]
I've encountered a bug when moving from the floor 1 to the floor 0; my avatar spawned on his desk instead of next to entrance door. 

My guess is that after a long time at a particular position it becomes a sort of "default location" on the map for your avatar. 

Reloading the application makes the bug go away.

**Comment by moufmouf** [comment]
Nope, but there is a new feature that enables a user to respawn at the same location when there is a network error.

We should try this:

- Connect
- Move to floor 1
- Cut and restore network connection
- Move to floor 0

Maybe this can reproduce your bug

**Comment by moufmouf** [comment]
See #146 for a fix regarding the reset position

**Comment by moufmouf** [comment]
Closed by #158
